// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTuF_GkSlzTZGKY_Um8WCTFnvZ2XqWvbQ',
    appId: '1:114570200566:web:1d481d477495b1aeaaf3d7',
    messagingSenderId: '114570200566',
    projectId: 'flutter-pet-project-c75d6',
    authDomain: 'flutter-pet-project-c75d6.firebaseapp.com',
    storageBucket: 'flutter-pet-project-c75d6.appspot.com',
    measurementId: 'G-1S9YDPBSYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABnVrpR_D5b_c9oVpT1am-k-Mok58AfRE',
    appId: '1:114570200566:android:c3900fd21e0238eaaaf3d7',
    messagingSenderId: '114570200566',
    projectId: 'flutter-pet-project-c75d6',
    storageBucket: 'flutter-pet-project-c75d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL38OXIZyrjRyzjlHd_IkzWBtbPPJEE_A',
    appId: '1:114570200566:ios:51ccc613b0f24257aaf3d7',
    messagingSenderId: '114570200566',
    projectId: 'flutter-pet-project-c75d6',
    storageBucket: 'flutter-pet-project-c75d6.appspot.com',
    iosClientId: '114570200566-gcsh8oeujpfej728qm88df3o1cq3jk04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDiplomMoneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL38OXIZyrjRyzjlHd_IkzWBtbPPJEE_A',
    appId: '1:114570200566:ios:51ccc613b0f24257aaf3d7',
    messagingSenderId: '114570200566',
    projectId: 'flutter-pet-project-c75d6',
    storageBucket: 'flutter-pet-project-c75d6.appspot.com',
    iosClientId: '114570200566-gcsh8oeujpfej728qm88df3o1cq3jk04.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDiplomMoneyTracker',
  );
}
